name = "novel-reader"
main = "src/worker.js"
compatibility_date = "2024-11-12"

# Workers 模式：通过 assets 提供 public 静态资源
assets = { directory = "public" }

# 可保留 nodejs 兼容（若无需要可移除）
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true