name = "wechat-auth-worker"
main = "worker.js"
compatibility_date = "2024-10-12"

[[d1_databases]]
binding = "DB"
database_name = "wechat_auth_db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"

[vars]
# OPENROUTER_API_KEY should be stored as a secret:
# wrangler secret put OPENROUTER_API_KEY
