name = "mobile-novel-reader"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[env.production]
name = "mobile-novel-reader"

[env.production.build]
command = ""

[[env.production.mounts]]
source = "./novels"
destination = "/novels"