# Cloudflare Pages 项目配置（使用 Pages Functions）
# 部署命令：npm run deploy  -> 等同于 `wrangler pages deploy .`
# 本地开发：npm run dev     -> 等同于 `wrangler pages dev --compatibility-date=2024-01-01`

name = "mobile-novel-reader"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 指定 Pages Functions 入口目录（functions 文件夹）
pages_build_output_dir = "."

[build]
command = ""

# Pages Functions 不需要设置 main（main 仅用于 Workers 模式）。
# 若你使用 Workers 部署而非 Pages，请改用：
# main = "functions/[[path]].js"

[env.production]
name = "mobile-novel-reader"

[env.production.build]
command = ""

# 将本地 novels 目录作为静态资源随代码发布，供 Pages Functions 通过 nodejs_compat 的 fs 读取
[[env.production.mounts]]
source = "./novels"
destination = "/novels"